### ISSUE TITLE
History for sopalama showing old STT_CS group task when he is working on STT_NS

### ISSUE THREAD

**Issue by spsither** [OpenPecha/pecha-tools-for-stt#15]
![WhatsApp Image 2024-02-27 at 4 05 12 PM](https://github.com/OpenPecha/pecha-tools-for-stt/assets/11909317/213de5fd-7c35-46b2-9652-c02267e38880)

**Comment by tentamdin** [comment]
Earlier history was not based on group, changed to get based on group id on lastest commit. That should solve the problem
